CI Github v1.0

diff --git a/.github/workflows/dev_branch.yaml b/.github/workflows/dev_branch.yaml
--- a/.github/workflows/dev_branch.yaml
+++ b/.github/workflows/dev_branch.yaml
@@ -27,11 +27,22 @@ jobs:
 
       - name: Install ChromeDriver
         run: |
+          set -e
           CHROME_VERSION=$(google-chrome --version | sed 's/Google Chrome //; s/\..*//')
           echo "Detected Chrome version: $CHROME_VERSION"
           CHROMEDRIVER_VERSION=$(wget -qO- "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
+          if [[ -z "$CHROMEDRIVER_VERSION" ]]; then
+            echo "Failed to fetch ChromeDriver version"
+            exit 1
+          fi
           echo "Detected ChromeDriver version: $CHROMEDRIVER_VERSION"
-          wget "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
+          URL="https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
+          echo "Download URL: $URL"
+          wget "$URL"
+          if [ $? -ne 0 ]; then
+            echo "Failed to download ChromeDriver"
+            exit 1
+          fi
           unzip chromedriver_linux64.zip
           sudo mv chromedriver /usr/local/bin/chromedriver
           chromedriver --version
